repo: biilmann/timespace.dk
branch: master
# Set up a reference for this more complex field so we can use it in multiple collections
linkField: &linkField 
  label: "Links"
  name: "links"
  widget: "list"
  fields:
    - {label: "Link text", name: "label", widget: "string"}
    - {label: "URL", name: "url", widget: "string"}
collections:
  - slug: "courses"
    label: "Course"
    folder: "_courses"
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Course Info", name: "info", widget: "markdown", class: "meta"}
      - {label: "Course Description", name: "body", widget: "markdown"}
      - *linkField # use the predefined linkField here
      - {label: "Files", name: "docs", widget: "files", folder: "docs/courses", optional: true}
  - slug: "articles"
    label: "Article"
    folder: "_articles"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h1", optional: true}
      - {label: "Publication Date", name: "date", widget: "date"}
      - {label: "Full Title", name: "full_title", widget: "string", tagname: "h3", optional: true}
      - {label: "Bibliography entry", name: "bib", widget: "markdown", class: "condensed"}
      - {label: "Article Abstract", name: "body", widget: "markdown"}
      - *linkField
      - {label: "Files", name: "docs", widget: "files", folder: "docs/articles"}
  - slug: "books"
    label: "Book"
    folder: "_books"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h1", class: "subtitle", optional: true}
      - {label: "Publication Date", name: "date", widget: "date"}
      - {label: "Full Title", name: "full_title", widget: "string", tagname: "h3", optional: true}
      - {label: "Bibliography entry", name: "bib", widget: "markdown", class: "condensed"}
      - {label: "Image", name: "image", widget: "image", folder: "img/media"}
      - {label: "Book Abstract", name: "body", widget: "markdown"}
  - slug: "pages"
    label: "Page"
    folder: "pages"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body Text", name: "body", widget: "markdown"}