repo: biilmann/timespace.dk
branch: links
collections:
  - slug: "courses"
    label: "Course"
    folder: "_courses"
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Course Info", name: "info", widget: "markdown", class: "meta"}
      - {label: "Course Description", name: "body", widget: "markdown"}
      - {label: "Links", name: "links", widget: "links"}
      - {label: "Files", name: "docs", widget: "files", folder: "docs/courses"}
  - slug: "articles"
    label: "Article"
    folder: "_articles"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h1 small"}
      - {label: "Publication Date", name: "date", widget: "date"}
      - {label: "Full Title", name: "full_title", widget: "string", tagname: "h3"}
      - {label: "Bibliography entry", name: "bib", widget: "markdown", class: "condensed"}
      - {label: "Article Abstract", name: "body", widget: "markdown"}
      - {label: "Footer", name: "footer", widget: "markdown"}
      - {label: "Links", name: "links", widget: "links"}
      - {label: "Files", name: "docs", widget: "files", folder: "docs/articles"}
  - slug: "books"
    label: "Book"
    folder: "_books"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h1 small"}
      - {label: "Publication Date", name: "date", widget: "date"}
      - {label: "Full Title", name: "full_title", widget: "string", tagname: "h3"}
      - {label: "Bibliography entry", name: "bib", widget: "markdown", class: "condensed"}
      - {label: "Image", name: "image", widget: "image", folder: "img/media"}
      - {label: "Book Abstract", name: "body", widget: "markdown"}
  - slug: "pages"
    label: "Page"
    folder: "pages"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body Text", name: "body", widget: "markdown"}